In [31]:
import pandas as pd
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns

In [32]:
df = pd.read_csv('/Users/darinaafanaseva/Desktop/DataScience/project/data/data2.csv')

In [33]:
pd.set_option('display.max_columns', None)

In [34]:
df = df[df['metro'].isna()==False]

In [35]:
df

,Unnamed: 0,ID,Rooms,"Square,m2",Floor_all,Floor_flat,Baclony,Bathroom,Children,Animal,"Height,m",Elevator,Parking,Furniture_in_the_rooms,Kitchen_furniture,Bath,Washing_machine,Air_conditioner,Dishwasher,TV,Internet,Telephone,Shower_cabin,Fridge,Price,Deposit,Public_services,Reno_design,Reno_euro,Reno_cosmetic,Reno_not_specified,Reno_no_renovation,Panel,Monolithic,Brick,Block,Monolithic_brick,Stalin,Old_fond,metro,adress,walk
0,0,271271157,4,200.0,16,5,0.0,0.0,1,1,3.00,5.0,1,1,1,1,1,1,1,1,1,1,1,1,500000.0,500000.0,1,1,0,0,0,0,0,1,0,0,0,0,0,м. Смоленская,"Москва, улица Новый Арбат, 27",9.0
1,1,271634126,4,198.0,16,5,0.0,3.0,1,0,3.50,2.0,1,1,1,1,1,1,1,1,1,0,1,1,500000.0,500000.0,1,1,0,0,0,0,0,0,0,0,1,0,0,м. Смоленская,"Москва, улица Новый Арбат, 27",8.0
2,2,271173086,4,200.0,16,5,0.0,3.0,1,0,3.20,1.0,1,1,1,1,1,1,1,1,1,1,1,1,500000.0,500000.0,0,0,1,0,0,0,0,0,0,0,0,0,0,м. Смоленская,"Москва, улица Новый Арбат, 27",7.0
3,3,272197456,4,170.0,6,5,0.0,3.0,0,1,3.20,1.0,1,1,1,1,1,1,1,1,1,1,1,1,400000.0,400000.0,0,0,1,0,0,0,0,0,0,0,0,0,0,м. Смоленская,"Москва, переулок Плотников, 21С1",3.0
4,4,273614615,2,58.0,26,12,0.0,2.0,0,0,3.90,2.0,0,1,1,1,1,0,1,1,1,0,1,1,225000.0,225000.0,1,0,1,0,0,0,1,0,0,0,0,0,0,м. Арбатская,"Москва, улица Новый Арбат, 15",7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23363,23363,215565511,1,35.0,14,10,1.0,1.0,0,0,3.00,2.0,0,1,1,1,1,1,0,0,1,0,0,1,42000.0,42000.0,1,0,1,0,0,0,0,0,0,0,0,0,0,м. Говорово,"Москва, Боровское шоссе, 2к7",8.0
23364,23364,274654844,1,38.7,18,5,1.0,1.0,0,0,3.00,2.0,0,1,1,1,1,0,0,1,0,0,0,1,45000.0,45000.0,1,0,1,0,0,0,0,1,0,0,0,0,0,м. Солнцево,"Москва, Производственная улица, 8к1",7.0
23365,23365,268679909,2,43.1,5,5,1.0,1.0,1,0,3.00,0.0,0,0,1,0,1,1,0,0,1,0,1,1,50000.0,50000.0,1,1,0,0,0,0,0,0,1,0,0,0,0,м. Солнцево,"Москва, Боровский проезд, 11",6.0
23366,23366,274807525,2,52.5,23,8,1.0,2.0,0,0,2.65,3.0,1,1,1,1,1,1,1,0,0,0,0,1,55000.0,50000.0,1,0,1,0,0,0,0,1,0,0,0,0,0,м. Солнцево,"Москва, улица Богданова, 6к1",11.0
23367,23367,274672243,2,90.0,23,6,1.0,1.0,1,1,3.00,3.0,0,1,1,1,1,1,1,1,1,0,0,1,57000.0,60000.0,1,0,0,1,0,0,1,0,0,0,0,0,0,м. Говорово,"Москва, улица Богданова, 2к1",10.0

In [36]:
df = df.drop('adress', axis=1)

In [37]:
df = df[df['metro'].isna()==False]
df_encoded = pd.get_dummies(df, columns=['metro'])

for col in df_encoded.select_dtypes(include=['bool']).columns:
    df_encoded[col] = df_encoded[col].astype(int)

In [38]:
!pip install transliterate

Requirement already satisfied: transliterate in /Users/darinaafanaseva/miniforge3/lib/python3.10/site-packages (1.10.2)
Requirement already satisfied: six>=1.1.0 in /Users/darinaafanaseva/miniforge3/lib/python3.10/site-packages (from transliterate) (1.16.0)

In [46]:
import pandas as pd
from transliterate import translit, get_available_language_codes

def is_latin(s):
    try:
        s.encode(encoding='utf-8').decode('ascii')
    except UnicodeDecodeError:
        return False
    else:
        return True


df_encoded.columns = [translit(name, 'ru', reversed=True) if not is_latin(name) else name for name in df_encoded.columns]
df_encoded.columns = df_encoded.columns.str.replace(' ', '_')

# Показать обновленные названия столбцов
print(df_encoded.columns)

Index(['Unnamed:_0', 'ID', 'Rooms', 'Square,m2', 'Floor_all', 'Floor_flat',
       'Baclony', 'Bathroom', 'Children', 'Animal',
       ...
       'metro_m._Schelkovskaja_', 'metro_m._Scherbinka_',
       'metro_m._Schukinskaja_', 'metro_m._Elektrozavodskaja_',
       'metro_m._Jugo-Vostochnaja_', 'metro_m._Jugo-Zapadnaja_',
       'metro_m._Juzhnaja_', 'metro_m._Jasenevo_', 'metro_m._Jahromskaja_',
       'metro_m._ulitsa_Narodnogo_opolchenija_'],
      dtype='object', length=318)